### ISSUE TITLE
export models / multivariate timeseries

### ISSUE THREAD

**Issue by luiztauffer** [aws-samples/amazon-forecast-samples#104]
Hi, thanks for this repository, has been quite helpful! I wonder if you could add examples / point me to good references for:

1. export the trained models
2. multivariate time series

**Comment by christy** [comment]
Hi Luiz, thank you, I can answer.

1. With Amazon Forecast, hosting trained models is done automatically in the service itself.  You cannot export the trained models out of the service.  You can view the model hyperparameters used by expanding the "training parameters" section on the Predictor page in UI.  Or you can issue API command describe_predictor().  If you don't see a setting in the "training parameters" section, then it has default value, documented under each algorithm > hyperparameters section https://docs.aws.amazon.com/forecast/latest/dg/aws-forecast-recipe-prophet.html

2. Multivariate time series (1 global model for multiple products at once) is only supported with the DeepNN algorithms.  We have:  DeepAR+ and CNN-QR.  The advantage of 1 global model for time series is ability to model item interdependencies - items that could be purchased together or cannibalize each other.  Note: Prophet allows related time series (e.g. weather), but the end result is a single model per time series you want to predict.  Amazon Forecast's DNN algorithms allow both related data (e.g. weather) as well as other targets (e.g. productA-location1, productA-location2, productB-location1, etc) to be all forecasted in a single model.  For more details see documentation about Target Time Series, Related Time Series, and Metadata.  https://docs.aws.amazon.com/forecast/latest/dg/howitworks-datasets-groups.html#howitworks-dataset-domainstypes

**Comment by luiztauffer** [comment]
Hi @christy , thank you for your reply, it was clarifying!
I understand now that the DeepNN models take into account the target variables simultaneously, in a way that predictions in one can affect the predictions in the other. It was not clear in the documentation, thanks for that! I’ve managed to train a DeepAR+ model for multiple targets plus related_data. 

I still don’t understand though if I should be using the extra attributes in the target_data for anything. If I add an extra attribute on target_data (an extra column), will it be treated as a target, or as a predictor independent variable? If it will be treated as a predictor independent variable, what is the difference of adding an attribute on target_data vs adding and attribute on related_data?

It surely is a shame that we can’t export the models. I understand that these same models are available through Sagemaker, and Sagemaker apparently allows us to export the trained models, do you know about that? I understand that there’s not much use in exporting the proprietary ones. 
The mais reason for this question is the unreasonable times that it takes to create import jobs and run new predictions with an already trained model, I was hoping to improve that inference pipeline outside of Forecast.

**Comment by christy** [comment]
Answering these separately.

Q1. If I add an extra attribute on target_data (an extra column), will it be treated as a target, or as a predictor independent variable? 
A. Extra columns in Target Time Series are treated as independent variables.  Note ITEM_ID is required and assumed to exist.  Make sure the extra forecast dimension ‘LOCATION_ID’ in this example, is selected as additional dimension on Train Predictor step > Predictor details > Forecast dimensions 
       ITEM_ID | LOCATION_ID | TIMESTAMP
* item1 | plant1 | time1
* item1 | plant1 | time2
* item1 | plant2 | time1
* item1 | plant2 | time2

— Metadata (does not vary with time) might look like this —
      ITEM_ID | LOCATION_ID | PLANT_SIZE | ITEM_FAMILY_GROUP
* item1 | plant1 | plant1_size | group1
* item1 | plant1 | plant1_size | group1
* item1 | plant2 | plant2_size | group1
* item1 | plant2 | plant2_size | group1

— Related data (varies with time) might look like this.  If you have an extra forecast dimension, such as location, then it must exist here also —
ITEM_ID | LOCATION_ID | TIMESTAMP | BLACK_FRIDAY_PROMOTION | wind_speed
* item1 | plant1 | time1 | 0 | 41
* item1 | plant1 | time2 | 1 | 32
* item1 | plant2 | time1 | 0 | 41
* item1 | plant2 | time2 | 1 | 32

Q2. It surely is a shame that we can’t export the models. I understand that these same models are available through Sagemaker, and Sagemaker apparently allows us to export the trained models, do you know about that? I understand that there’s not much use in exporting the proprietary ones.
A2. The DeepAR model exported in Sagemaker is slightly different from the DeepAR+ model trained in managed service Amazon Forecast.  Yes, execution times do make this a hard service to run interactively.  

Have you seen our automation solution that uses S3 trigger, Lambda, Step Functions, SNS?  https://aws.amazon.com/solutions/implementations/improving-forecast-accuracy-with-machine-learning

**Comment by luiztauffer** [comment]
If extra columns in TARGET_DATA are treated as independent variables, what is the difference of adding an attribute on TARGET_DATA vs adding and attribute on RELATED_DATA?
Does it make any difference for the models?

With attributes on RELATED_DATA I know I should add the future timestamps values during the forecast window. Is it the same for extra attributes on TARGET_DATA?

thank you once more for such detailed replies!

**Comment by christy** [comment]
Target Time Series is only for the dependent variable, "target_value" of items (Y1, Y2), by extra dimensions if you have them, and by time.

Related Time Series is for the independent variables, (X1, X2, X3, X4, X5), which vary by items (Y1, Y2), by dimensions, and by time.  Example "promotion1", "promotion2" vary by item (Y1, Y2) and by time.  Yes, Related Time Series need estimated future values.

**Comment by luiztauffer** [comment]
then what are extra attributes (extra columns) in the target data used for? I'm not talking about `timestamps`, `item_id` and `target_value`, I'm talking about extra columns that can be added beyond those

**Comment by christy** [comment]
The extra columns in Target Time Series (TTS) are interpreted as forecast dimensions.  Each combination of time, item_id, and extra forecast dimension creates a new time series to be forecasted (along with accuracy metrics per time series).  E.g. 5 items, 5 locations, 5 regions = 5 * 5 time series with extra dimension region.  

How you organize your data is up to you, and in this example does not affect accuracy.  Pro: putting region in TTS, you can explicitly query in the UI (by item, location, and region) for that particular forecast.  Con:  Region is more intuitive as metadata, which in turn is a shorter file to input than the expanded TTS.  During pre-processing or post-processing exported forecasts, can be joined to metadata to drill up/down as you like.  It's more typical customers export forecasts to their own BI tools for exploring than the UI tool.

I'm going to close this issue since it's not about code.  For more general Q&A about Amazon Forecast, please see our Forum https://forums.aws.amazon.com/forum.jspa?forumID=348.  Thanks.

**Comment by luiztauffer** [comment]
thanks again for all the help @christy !
