### ISSUE TITLE
Error when trying to create object with same name as previously deleted object

### ISSUE THREAD

**Issue by luiztauffer** [aws-samples/amazon-forecast-samples#105]
I am getting `CreateDatasetImportJob` errors when trying to create ImportJobs (and in some cases Datasets) with the same name of a previously deleted ImportJobs (and sometimes Datasets). The delete is done using the routine described in the notebook 4.Cleanup

Steps:
1. create a Dataset with name `my_target_ds` using `create_dataset()` 
2. create a ImportJob with name `MY_TARGET_DS_IMPORT_JOB` using `create_dataset_import_job()` 
3. delete the ImportJob using `delete_dataset_import_job()`
4. delete the Dataset using `delete_dataset()`
5. Step 1 again
6. Step 2 again

```
Error An error occurred (ResourceAlreadyExistsException) when calling the CreateDatasetImportJob operation: A dataset import job already exists with the arn: .......:dataset-import-job/MY_TARGET_DS_IMPORT_JOB
```

This error does not happen if I delete Dataset and ImportJOb manually on the console

**Comment by christy** [comment]
Delete API call is not synchronous. You need to wait a few minutes for backend workflow to complete job before re-using a deleted name.

In our github we have utility wait functions especially for this reason to wait for API calls to finish, see notebooks/common/util.  To see an example for delete APIs, scroll to bottom of my notebook https://github.com/aws-samples/amazon-forecast-samples/blob/master/notebooks/advanced/Weather_index/1.%20Training%20your%20model%20with%20Weather%20Index.ipynb
------

# Delete the target time series import job
util.wait_till_delete(lambda: forecast.delete_dataset_import_job(DatasetImportJobArn=ts_dataset_import_job_arn))

# Delete the target time series datasets
util.wait_till_delete(lambda: forecast.delete_dataset(DatasetArn=ts_dataset_arn))

**Comment by luiztauffer** [comment]
Hi @christy 
yes I know, I am using the waiting function and I am making sure the object is not existing anymore (as per request response using the describe function) before trying to create a new one with the same name
this does not solve the problem

**Comment by luiztauffer** [comment]
yes I am using `util.wait_till_delete()`, sorry for the confusion.
The objects are being deleted, I can open the console and they're not there anymore, also otherwise the objects that are locked by them wouldn't be able to be deleted, and they are. What it feels like is that there is a bug in waiting times from the aws side, I was wondering if it could be solved by some type of testing from the client side.
Like, do I need to wait one hour to create another object with the same same? 
What is the difference between delete a Dataset manually on Console or programmatically using boto3? I wouldn't expect it to be different

**Comment by christy** [comment]
I've forwarded to a developer.  They're looking into it.  Thanks.

**Comment by christy** [comment]
Our developer tried to re-create the problem.  He says to make sure notebooks all use the same Region?  

"i've tested several times using the notebook to create and delete Dataset and DatasetImportJob, repeated several times, didn't meet the same issue. So I don't think there is any error within our system. One thing we can ask customer to check is the "region" they specified in notebook 1 and notebook 4. As I can see these two should be same if customer use these notebooks in order, while it's a potential reason why customer is meeting this kind error, that customer used create and delete notebook under different region."
