### ISSUE TITLE
Validation error when calling forecast.create_predictor with CNN-QR algorithm_arn

### ISSUE THREAD

**Issue by rayaws** [aws-samples/amazon-forecast-samples#118]
When using Compare_Multiple_Models notebook, I run into below error when calling “forecast.create_predictor” from SageMaker, with additional algorithm ("CNN-QR") in "algo" array.  

>` An error occurred (ValidationException) when calling the CreatePredictor operation: 1 validation error detected: Value ‘compare_multiple_models_CNN-QR_algo’ at ‘predictorName’ failed to satisfy constraint: Member must satisfy regular expression pattern: ^[a-zA-Z][a-zA-Z0-9_]*
`

Looks like the arn is correct based on document, and a different error message when trying different algo text.  The regular expression pattern seems to not support "-" character.  May need to change the validation to ^[a-zA-Z][a-zA-Z0-9_-]* to support CNN-QR algo arn.

>` InvalidInputException: An error occurred (InvalidInputException) when calling the CreatePredictor operation: Invalid Algorithm ARN specified: arn:aws:forecast:::algorithm/CNN. Options: arn:aws:forecast:::algorithm/CNN-QR,arn:aws:forecast:::algorithm/Deep_AR_Plus,arn:aws:forecast:::algorithm/NPTS,arn:aws:forecast:::algorithm/ETS,arn:aws:forecast:::algorithm/ARIMA,arn:aws:forecast:::algorithm/Prophet
`

**Comment by christy** [comment]
From above error message, the error was in the call to Algorithm itself, not the name you called your predictor.  The API call should be "arn:aws:forecast:::algorithm/CNN-QR".  Note that is different naming convention from "arn:aws:forecast:::algorithm/Deep_AR_Plus" which has all underscores instead of "-".  API call names have inconsistent style, sorry about that.

**Comment by rayaws** [comment]
Thanks @christy.

Just figured out that the first error is for predictorName, which is any free text but has to comply to that RegEx validation.  The second error is about the algo arn, that has to be exactly from the defined list.  Thus I added a replace command to change '-' to '_' for predictorName (and not the ARN), and it works well.


```
algos = ['CNN-QR', 'ARIMA', 'Prophet', 'ETS', 'NPTS', 'Deep_AR_Plus']
 
predictors = {a:{} for a in algos}
 
for p in predictors:
     predictors[p]['predictor_name'] = project + '_' + p.replace('-','_') + '_algo'
     predictors[p]['algorithm_arn'] = 'arn:aws:forecast:::algorithm/' + p

pp.pprint(predictors)
```
