### ISSUE TITLE
How can I answer 'what if' questions?

### ISSUE THREAD

**Issue by NicolaiHarich** [aws-samples/amazon-forecast-samples#12]
Some algorithms e.g. prophet or DeepAR are able to incorporate exogenous variables (e.g. special events). 
This enables us in principal to make 'what if' simulations.

From the API documentation it's not clear for me how those variables can be incorporated into the future dataframe. I can't see any way to provide exogenous variables.
As I understood 'deploy_predictor' starts a forecast directly after the last training point for the specified horizon - Is that true? How can I change the start point for the forecast (without expensive retraining)?

It would be great if you can help me with this question. An example notebook would be even better ;-)
Thank you for your great work!

**Comment by akhilrazdan** [comment]
Thank you for your question. 
This is how ‘What-If’ will work by brute force with the current APIs: 
* Forecast has a dataset type (i.e. Related Time Series) that supports adding related features like price, promotion etc.
* In this dataset the you can account for future values of said variables above
* Essentially you can setup multiple scenarios (using different dataset groups) each with a new related dataset like below:
  * Related Dataset 1: Mean Price and Promotion
  * Related Dataset 2: +10% Price and No Promotion
 * Related Dataset 3: -10% Price and increased Promotion
* For each scenario, a separate predictor needs to be created which can generate its own forecast
* This in essence will get you to a ‘What-If’ scenario

We will be working on having a what-if directly built into our real time inferencing in the future, but it hasn't been fully planned in yet.
