### ISSUE TITLE
Where is the updated python SDK for the July 22nd 2019 API update?

### ISSUE THREAD

**Issue by divv** [aws-samples/amazon-forecast-samples#17]
There is currently a message about a recent API update on the AWS Forecast documentation:
> The Amazon Forecast API will undergo significant changes during scheduled maintenance occurring from 10 AM on 7/22/19 until 10 AM on 7/23/19. During maintenance, access to the Forecast APIs and console might be interrupted.
> 
> After 7/22/19, your Forecast resources (datasets, predictors, and forecasts) will no longer be available. However, you can save your forecasts for future use. We recommend using the CreateForecastExportJob API to save them to your S3 bucket before 7/22/19.
> 
> After maintenance concludes, before using the APIs, you must download a new SDK and modify your existing code to reflect the syntax changes. If you use only the console, you won’t need to make any changes.
> 
> We will provide new API documentation before scheduled maintenance begins. If you have questions, contact <forecastpreview-support@amazon.com>

It says "you must download a new SDK and modify your existing code to reflect the syntax changes".

Where is the latest SDK for Python?

**Comment by easyj2j** [comment]
The preface to that quote: "After maintenance concludes". It will be provided then.

**Comment by akhilrazdan** [comment]
We're currently working on it. Yes, as mentioned, you will have it by 10 AM PT tomorrow.
