### ISSUE TITLE
basic/Tutorial Evaluating the Predictor updates

### ISSUE THREAD

**Issue by LameLemon** [aws-samples/amazon-forecast-samples#177]
Hello, I'm using the 4 [basic/Tutorial](https://github.com/aws-samples/amazon-forecast-samples/tree/master/notebooks/basic/Tutorial) notebooks to run a demo and encountered a few errors along the way.

- In 3.Evaluating_Your_Predictor, `forecast_arn` doesn't exist. This can be replaced with `forecast_arn_deep_ar` variable from the previous step.
- In 3.Evaluating_Your_Predictor, `"data/item-demand-time-validation.csv"` doesn't exist. This can be replaced with `"data/item-demand-time-validation.csv"`. However this does not give the desired results, see image below.
    -  ![image](https://user-images.githubusercontent.com/35942108/133461265-6d7a0f42-670f-4ad4-8bfc-1e3c63e20190.png)
    - A new new file for validation can be created in 1.Importing_Your_Data with the correct time range for validation.
    - The sliced time range in 3.Evaluating_Your_Predictor for the df used to plot the graph can then be updated to reflect the validation data file. This gives us the correct graph, see image below.
    - ![image](https://user-images.githubusercontent.com/35942108/133463345-6c488aa2-c24a-41f0-8511-ceae1991dc75.png)

 
Hopefully I was able to explain myself well. I can make the required changes and submit  a PR.

:slightly_smiling_face:

**Comment by chrisking** [comment]
Excellent callout, if you make the PR I'll be happy to review and merge!

**Comment by LameLemon** [comment]
Fixes have been merged!
