### ISSUE TITLE
amazon-forecast-samples/ml_ops/visualization_blog/testing-data/params_example.json file missing apostrophe on DatasetType

### ISSUE THREAD

**Issue by Barnabas02** [aws-samples/amazon-forecast-samples#201]
Please correct
"DatasetType": "'TARGET_TIME_SERIES'|'RELATED_TIME_SERIES|ITEM_METADATA'",

to
"DatasetType": "'TARGET_TIME_SERIES'|'RELATED_TIME_SERIES'|'ITEM_METADATA'",

**Comment by czlaugh** [comment]
Corrected, please review.  Thank you.
