### ISSUE TITLE
Error while importing util. ModuleNotFoundError for util

### ISSUE THREAD

**Issue by vaibhavsalvi** [aws-samples/amazon-forecast-samples#202]
![Screenshot ModuleNotFoundError util](https://user-images.githubusercontent.com/9345495/165599816-8789be66-d15c-4f0b-b55f-33810aab9c10.png)

Not able to import util. 
I have printed out my path, have the same structure of the sample as in Git.
Tried using PYTHONPATH and  copying the util folder to the Getting Started, got same error.

**Comment by czlaugh** [comment]
Hello.  Can you clone the entire repo to your local dev environment with https://github.com/aws-samples/amazon-forecast-samples.git ?  Inside this repo, the util is located inside the ./notebooks/common folder.  If the entire repo is local, this relative path should work when running the notebook.   Please advise outcome.  Thank you.

**Comment by WilliamLwj** [comment]
> Hello. Can you clone the entire repo to your local dev environment with https://github.com/aws-samples/amazon-forecast-samples.git ? Inside this repo, the util is located inside the ./notebooks/common folder. If the entire repo is local, this relative path should work when running the notebook. Please advise outcome. Thank you.

Hi it works! Thank you!
