### ISSUE TITLE
Complex Open Dataset

### ISSUE THREAD

**Issue by chrisking** [aws-samples/amazon-forecast-samples#31]
Identify a time-series oriented dataset with the following types of information:

1. Target Time Series
1. Related Time Series
1. Item Metadata

These will be used in other notebooks to illustrate their impact and usage with various algorithms.

**Comment by athewsey** [comment]
A couple of potential suggestions:

[**UCI Beijing Multi-Site Air-Quality:**](http://archive.ics.uci.edu/ml/datasets/Beijing+Multi-Site+Air-Quality+Data) 6 pollutant reading types x 5 station locations could be interpreted as 30 items with some linking metadata. 6 relevant meteorological variables could be interpreted as related timeseries.

**UCI Online Retail Store Datasets [One](http://archive.ics.uci.edu/ml/datasets/Online+Retail) and [Two](http://archive.ics.uci.edu/ml/datasets/Online+Retail+II):** Two years (in the second version) of per-SKU, per-customer sales data for an online store in the UK. Could use `UnitPrice` (listed at point of sale) to derive related timeseries and/or experiment with holiday calendars. Could explore deriving product metadata features from the `Description` text.
