### ISSUE TITLE
WhatIf Analysis Notebook

### ISSUE THREAD

**Issue by chrisking** [aws-samples/amazon-forecast-samples#35]
Create a notebook that illustrates how to include metadata for related time series information to perform a what if analysis.

**Comment by PeggyFan** [comment]
Is it possible to include a what-if feature change in the related time series? So far metadata has no time dimension (only related to item_id). Can I make forecast using different sets values of a feature in related time series? For example, I want to test different sets of temperatures in the forecast period (varies by day) for daily sales, is it possible to make forecasts for the same item but for different set of parameters? It seems you can only make 1 forecast for each item_id at a time?

**Comment by shimomut** [comment]
@PeggyFan
To do the what-if analysis with Forecast, following steps have to be executed.

1) Prepare CSV files. For related time series, you need to prepare 2 versions (e.g. different item prices for the forecast period.)
2) Create Datasets, import CSV files into them. This time, use the first version of the related time series.
3) Create Predictor.
4) Create Forecast. (forecast #1)
5) Import 2nd version of the related time series data.
6) Create Forecast. (forecast #2)
7) Compare forecasts between #1 and #2.
