### ISSUE TITLE
Coldstart Notebook

### ISSUE THREAD

**Issue by chrisking** [aws-samples/amazon-forecast-samples#36]
Using a dataset with item metadata illustrate how to predict cold start items in a notebook.

**Comment by PeggyFan** [comment]
Hi, I ran the notebook but failed to create forecasts for the`coldStartTargetData.csv`. I see that it was imported as a target time series to`coldstart_demo_grp_2`, but when I called `create.forecast` it creates forecasts for the original target time series, NOT the coldStartTargetData. 

So there are two datasets created as data type `TARGET_TIME_SERIES`, how do I make the predictor to use the target time series I want? I cannot delete the original target time series without deleting the predictor (which defeats the purpose of using it to predict coldstart items). Please advise.

**Comment by shimomut** [comment]
@PeggyFan,
I re-checked the notebook ("8.Forecast with Cold Start Items.ipynb"), but was not able to reproduce the issue.

Please try to run the notebook again with clean check-out status (no modification), and check if the issue still happens. The notebook should be creating just one TARGET_TIME_SERIES dataset, and creating two DatasetImportJobs. It's worth checking the output of forecast.describe_dataset_group() API, and confirm that the TARGET_TIME_SERIES dataset included in the dataset-group is intended one.

Please let us know if you still see the issue.

**Comment by PeggyFan** [comment]
The issue has been resolved after I started the notebook afresh.
