### ISSUE TITLE
Forecast both units and price of products

### ISSUE THREAD

**Issue by agamat** [aws-samples/amazon-forecast-samples#42]
Hi,
When forecasting units of many forecast dimensions, is it possible to also forecast price (rather than treating price as related series)?

Is it possible to illustrate it in the python notebook?

thank you and kind regards
Aga

**Comment by akhilrazdan** [comment]
For now, you can only forecast 1 variable, and use others as Related time series. 

Have you tried our Related time series notebook : 
https://github.com/aws-samples/amazon-forecast-samples/blob/master/notebooks/6.Incorporating_Related_Time_Series_dataset_to_your_Predictor.ipynb
