### ISSUE TITLE
2 different data frequencies

### ISSUE THREAD

**Issue by agamat** [aws-samples/amazon-forecast-samples#43]
Hi,

Can Amazon Forecast use **2 different frequencies** of input target data,
for example weekly and monthly (you get weekly faster for the current month than monthly - 
you need to end until the end of the month )?

**Comment by chrisking** [comment]
So if your forecast is monthly, you can certainly provide daily or weekly results, but you would still only predict on the monthly delta. You cant provide monthly and then try to predict daily however.
