### ISSUE TITLE
Issue Seeing Evaluate the Predictor Notebook

### ISSUE THREAD

**Issue by thepersonclass** [aws-samples/amazon-forecast-samples#46]
I can't pull this up in Chrome. https://github.com/aws-samples/amazon-forecast-samples/blob/master/notebooks/3.Evaluating_Your_Predictor.ipynb

**Comment by chrisking** [comment]
Can you be a bit more specific? Do you mean the preview page does not render? If so that's a common issue in GH rendering of the notebooks. You should be able to view it in any Jupyter environment.

**Comment by thepersonclass** [comment]
Sorry you can close this not sure if it was an internet issue or not. It wasn't loading the file in Github in the browser. Now it can load it like the other pages. Thanks for the quick response.

**Comment by chrisking** [comment]
Closing, no worries thanks for getting back as well!
