### ISSUE TITLE
Predictor ARN Issue

### ISSUE THREAD

**Issue by thepersonclass** [aws-samples/amazon-forecast-samples#51]
Hello,

I am getting this issue when I run line 15 in notebook 2. 

```
predictor_arn = predictorArn
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-15-70e3f3e2c98d> in <module>()
----> 1 predictor_arn = predictorArn

NameError: name 'predictorArn' is not defined
```
I am running the notebook in jupyterlab in AWS Sagemaker. Please let me know if I am missing something. I didn't see the above var any where in your code.

I skipped over this line and was able to complete the lab. I dont see that its being used anywhere. Might not be needed.

Thanks for the help!

Dan

**Comment by chrisking** [comment]
It is actually not needed, it was a fragment from a working copy that should not have been introduced. Simply delete the line and you are good to go!

**Comment by chrisking** [comment]
Will be fixed with the merge of https://github.com/aws-samples/amazon-forecast-samples/pull/52
