### ISSUE TITLE
UnknownServiceError

### ISSUE THREAD

**Issue by pmleffers** [aws-samples/amazon-forecast-samples#82]
forecast = session.client(service_name='forecast') 
UnknownServiceError: Unknown service: 'forecast'. Valid service names are: acm, acm-pca, alexaforbusiness, amplify, apigateway, apigatewaymanagementapi, apigatewayv2, application-autoscaling, application-insights, appmesh, appstream, appsync, athena, autoscaling, autoscaling-plans, backup...etc.

**Comment by chrisking** [comment]
Can you tell us where you are running this code and what notebook has caused this? I'm guessing your installation of boto3 is out of date and should be upgraded.
